# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiApplicationWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(732, 531)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(700, 530))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/resources/Icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.splitter_2 = QtGui.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.controlTabWidget = QtGui.QTabWidget(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlTabWidget.sizePolicy().hasHeightForWidth())
        self.controlTabWidget.setSizePolicy(sizePolicy)
        self.controlTabWidget.setMinimumSize(QtCore.QSize(260, 0))
        self.controlTabWidget.setMaximumSize(QtCore.QSize(368, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.controlTabWidget.setFont(font)
        self.controlTabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.controlTabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.controlTabWidget.setObjectName(_fromUtf8("controlTabWidget"))
        self.splitter = QtGui.QSplitter(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setMinimumSize(QtCore.QSize(320, 420))
        self.splitter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setChildrenCollapsible(True)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.uiGraphicsTabWidget = QtGui.QTabWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(255)
        sizePolicy.setHeightForWidth(self.uiGraphicsTabWidget.sizePolicy().hasHeightForWidth())
        self.uiGraphicsTabWidget.setSizePolicy(sizePolicy)
        self.uiGraphicsTabWidget.setMinimumSize(QtCore.QSize(335, 370))
        self.uiGraphicsTabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.uiGraphicsTabWidget.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.uiGraphicsTabWidget.setFont(font)
        self.uiGraphicsTabWidget.setObjectName(_fromUtf8("uiGraphicsTabWidget"))
        self.uiGraphicsTab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiGraphicsTab.sizePolicy().hasHeightForWidth())
        self.uiGraphicsTab.setSizePolicy(sizePolicy)
        self.uiGraphicsTab.setMinimumSize(QtCore.QSize(330, 360))
        self.uiGraphicsTab.setObjectName(_fromUtf8("uiGraphicsTab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.uiGraphicsTab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.uiGraphicsTabWidget.addTab(self.uiGraphicsTab, _fromUtf8(""))
        self.gridLayout.addWidget(self.splitter_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 732, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/resources/exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon1)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionUser = QtGui.QAction(MainWindow)
        self.actionUser.setObjectName(_fromUtf8("actionUser"))
        self.actionLogger = QtGui.QAction(MainWindow)
        self.actionLogger.setCheckable(True)
        self.actionLogger.setChecked(True)
        self.actionLogger.setObjectName(_fromUtf8("actionLogger"))
        self.actionTimeSet = QtGui.QAction(MainWindow)
        self.actionTimeSet.setObjectName(_fromUtf8("actionTimeSet"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionAdd_User = QtGui.QAction(MainWindow)
        self.actionAdd_User.setObjectName(_fromUtf8("actionAdd_User"))
        self.actionRemove_User = QtGui.QAction(MainWindow)
        self.actionRemove_User.setObjectName(_fromUtf8("actionRemove_User"))
        self.actionTutorial = QtGui.QAction(MainWindow)
        self.actionTutorial.setObjectName(_fromUtf8("actionTutorial"))
        self.actionInbox_Stats = QtGui.QAction(MainWindow)
        self.actionInbox_Stats.setCheckable(True)
        self.actionInbox_Stats.setChecked(True)
        self.actionInbox_Stats.setObjectName(_fromUtf8("actionInbox_Stats"))
        self.actionConnection_Settings = QtGui.QAction(MainWindow)
        self.actionConnection_Settings.setObjectName(_fromUtf8("actionConnection_Settings"))
        self.actionConnection_Settings_2 = QtGui.QAction(MainWindow)
        self.actionConnection_Settings_2.setObjectName(_fromUtf8("actionConnection_Settings_2"))
        self.menuFile.addAction(self.actionExit)
        self.menuSettings.addAction(self.actionAdd_User)
        self.menuSettings.addAction(self.actionRemove_User)
        self.menuView.addAction(self.actionLogger)
        self.menuView.addAction(self.actionInbox_Stats)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionTutorial)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.controlTabWidget.setCurrentIndex(-1)
        self.uiGraphicsTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Smart Scan", None))
        self.uiGraphicsTabWidget.setTabText(self.uiGraphicsTabWidget.indexOf(self.uiGraphicsTab), _translate("MainWindow", "Ad Tab", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.menuHelp.setToolTip(_translate("MainWindow", "Help", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionUser.setText(_translate("MainWindow", "User Info", None))
        self.actionLogger.setText(_translate("MainWindow", "Logger", None))
        self.actionLogger.setToolTip(_translate("MainWindow", "View Logger", None))
        self.actionTimeSet.setText(_translate("MainWindow", "Time", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences", None))
        self.actionAdd_User.setText(_translate("MainWindow", "Add Gmail ID", None))
        self.actionRemove_User.setText(_translate("MainWindow", "Remove Gmail ID", None))
        self.actionTutorial.setText(_translate("MainWindow", "Tutorial", None))
        self.actionInbox_Stats.setText(_translate("MainWindow", "Inbox Stats", None))
        self.actionConnection_Settings.setText(_translate("MainWindow", "Connection Settings", None))
        self.actionConnection_Settings_2.setText(_translate("MainWindow", "Connection Settings", None))

