# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiUserInfo_modified_2.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(336, 936)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        Dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/resources/Icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.splitter_2 = QtGui.QSplitter(Dialog)
        self.splitter_2.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setMinimumSize(QtCore.QSize(0, 300))
        self.splitter_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.splitter_2.setLineWidth(1)
        self.splitter_2.setMidLineWidth(0)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.verticalLayoutWidget = QtGui.QWidget(self.splitter_2)
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_5.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.userInfo = QtGui.QGroupBox(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userInfo.sizePolicy().hasHeightForWidth())
        self.userInfo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.userInfo.setFont(font)
        self.userInfo.setObjectName(_fromUtf8("userInfo"))
        self.gridLayout = QtGui.QGridLayout(self.userInfo)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.usersCombo = QtGui.QComboBox(self.userInfo)
        self.usersCombo.setObjectName(_fromUtf8("usersCombo"))
        self.gridLayout.addWidget(self.usersCombo, 0, 1, 1, 1)
        self.connectButton = QtGui.QPushButton(self.userInfo)
        self.connectButton.setText(_fromUtf8(""))
        self.connectButton.setFlat(True)
        self.connectButton.setObjectName(_fromUtf8("connectButton"))
        self.gridLayout.addWidget(self.connectButton, 2, 1, 1, 1)
        self.labelUsers = QtGui.QLabel(self.userInfo)
        self.labelUsers.setObjectName(_fromUtf8("labelUsers"))
        self.gridLayout.addWidget(self.labelUsers, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.userInfo)
        self.userStatus = QtGui.QGroupBox(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userStatus.sizePolicy().hasHeightForWidth())
        self.userStatus.setSizePolicy(sizePolicy)
        self.userStatus.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.userStatus.setFont(font)
        self.userStatus.setObjectName(_fromUtf8("userStatus"))
        self.gridLayout_2 = QtGui.QGridLayout(self.userStatus)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.emailsLabel = QtGui.QLabel(self.userStatus)
        self.emailsLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.emailsLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.emailsLabel.setFont(font)
        self.emailsLabel.setObjectName(_fromUtf8("emailsLabel"))
        self.gridLayout_2.addWidget(self.emailsLabel, 1, 0, 1, 1)
        self.stopScanButton = QtGui.QPushButton(self.userStatus)
        self.stopScanButton.setMinimumSize(QtCore.QSize(0, 35))
        self.stopScanButton.setMaximumSize(QtCore.QSize(145, 22))
        self.stopScanButton.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/resources/Sq.-Pause-n-Switch.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopScanButton.setIcon(icon1)
        self.stopScanButton.setIconSize(QtCore.QSize(160, 60))
        self.stopScanButton.setFlat(True)
        self.stopScanButton.setObjectName(_fromUtf8("stopScanButton"))
        self.gridLayout_2.addWidget(self.stopScanButton, 4, 1, 1, 1)
        self.userLabel = QtGui.QLabel(self.userStatus)
        self.userLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.userLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.userLabel.setFont(font)
        self.userLabel.setObjectName(_fromUtf8("userLabel"))
        self.gridLayout_2.addWidget(self.userLabel, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 4, 2, 1, 1)
        self.scanButton = QtGui.QPushButton(self.userStatus)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scanButton.sizePolicy().hasHeightForWidth())
        self.scanButton.setSizePolicy(sizePolicy)
        self.scanButton.setMinimumSize(QtCore.QSize(0, 35))
        self.scanButton.setMaximumSize(QtCore.QSize(133, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.scanButton.setFont(font)
        self.scanButton.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/resources/Sq.Start.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.scanButton.setIcon(icon2)
        self.scanButton.setIconSize(QtCore.QSize(450, 33))
        self.scanButton.setDefault(False)
        self.scanButton.setFlat(True)
        self.scanButton.setObjectName(_fromUtf8("scanButton"))
        self.gridLayout_2.addWidget(self.scanButton, 4, 0, 1, 1)
        self.userValue = QtGui.QLabel(self.userStatus)
        self.userValue.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.userValue.setFont(font)
        self.userValue.setObjectName(_fromUtf8("userValue"))
        self.gridLayout_2.addWidget(self.userValue, 0, 1, 1, 2)
        self.emailsValue = QtGui.QLabel(self.userStatus)
        self.emailsValue.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.emailsValue.setFont(font)
        self.emailsValue.setObjectName(_fromUtf8("emailsValue"))
        self.gridLayout_2.addWidget(self.emailsValue, 1, 1, 1, 2)
        self.verticalLayout_5.addWidget(self.userStatus)
        self.groupBox = QtGui.QGroupBox(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.checkBoxEnableSound = QtGui.QCheckBox(self.groupBox)
        self.checkBoxEnableSound.setObjectName(_fromUtf8("checkBoxEnableSound"))
        self.verticalLayout_2.addWidget(self.checkBoxEnableSound)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.deleteMailOff = QtGui.QRadioButton(self.groupBox)
        self.deleteMailOff.setChecked(True)
        self.deleteMailOff.setObjectName(_fromUtf8("deleteMailOff"))
        self.horizontalLayout_3.addWidget(self.deleteMailOff)
        self.deleteMailOn = QtGui.QRadioButton(self.groupBox)
        self.deleteMailOn.setObjectName(_fromUtf8("deleteMailOn"))
        self.horizontalLayout_3.addWidget(self.deleteMailOn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.userInfoTableView = QtGui.QTableView(self.groupBox)
        self.userInfoTableView.setObjectName(_fromUtf8("userInfoTableView"))
        self.verticalLayout_2.addWidget(self.userInfoTableView)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.refreshBtn = QtGui.QToolButton(self.groupBox)
        self.refreshBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.refreshBtn.setObjectName(_fromUtf8("refreshBtn"))
        self.horizontalLayout.addWidget(self.refreshBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.loggerTextArea = QtGui.QTextEdit(self.groupBox)
        self.loggerTextArea.setObjectName(_fromUtf8("loggerTextArea"))
        self.verticalLayout_2.addWidget(self.loggerTextArea)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.verticalLayout.addWidget(self.splitter_2)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.userInfo.setTitle(_translate("Dialog", "User Information", None))
        self.usersCombo.setToolTip(_translate("Dialog", "Added Users", None))
        self.connectButton.setToolTip(_translate("Dialog", "Connect To Server", None))
        self.labelUsers.setText(_translate("Dialog", "Users", None))
        self.userStatus.setTitle(_translate("Dialog", "User Status", None))
        self.emailsLabel.setText(_translate("Dialog", "Emails Read", None))
        self.stopScanButton.setToolTip(_translate("Dialog", "Click Here To Stop Scan", None))
        self.userLabel.setText(_translate("Dialog", "Username", None))
        self.scanButton.setToolTip(_translate("Dialog", "Start Scan", None))
        self.userValue.setToolTip(_translate("Dialog", "Username", None))
        self.userValue.setText(_translate("Dialog", "Smart Ad Viewer", None))
        self.emailsValue.setToolTip(_translate("Dialog", "Total Read Emails", None))
        self.emailsValue.setText(_translate("Dialog", "0", None))
        self.groupBox.setTitle(_translate("Dialog", "User Settings", None))
        self.checkBoxEnableSound.setText(_translate("Dialog", "Mute Audio", None))
        self.label.setText(_translate("Dialog", "Delete Read Emails:", None))
        self.deleteMailOff.setText(_translate("Dialog", "Off", None))
        self.deleteMailOn.setText(_translate("Dialog", "On", None))
        self.userInfoTableView.setToolTip(_translate("Dialog", "Inbox Stats", None))
        self.refreshBtn.setText(_translate("Dialog", "Refresh", None))
        self.loggerTextArea.setToolTip(_translate("Dialog", "Logger", None))
        self.loggerTextArea.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#00aaff;\">Welcome To Smart Ad Viewer!</span></p></body></html>", None))

import all_resources_rc
